[package]
name = "secretsmanager-helloworld"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Nas Taibi <naceredd@amazon.com>"]
edition = "2018"
description = "Example usage of the SecretManager service"

[dependencies]
secretsmanager = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.4-alpha", package = "aws-sdk-secretsmanager" }
aws-hyper = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.4-alpha", package = "aws-hyper" }
tokio = { version = "1", features = ["full"]}
# optional
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
