[package]
name = "step-function-code-examples"
version = "0.1.0"
authors = ["Daniele Frasca <https://github.com/ymwjbxxq/>"]

[dependencies]
aws-config = "0.6.0"
aws-sdk-sfn = "0.6.0"
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
