[package]
name = "localstack-example"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

[dependencies]
aws-config = "0.2.0"
aws-sdk-s3 = "0.2.0"
aws-sdk-sqs = "0.2.0"
aws-types = "0.2.0"
aws-smithy-http = "0.32.0"
tokio = { version = "1", features = ["full"] }
http = "0.2"
tracing-subscriber = "0.2"
